# Ch2 预备知识

In [1]:
# Getting Started:
import torch
import numpy as np

## $\S2.1$ 数据操作

In [2]:
# 张量对象
x = torch.arange(12)
## 张量的形状：
x.shape
## 张量元素的个数：
x.numel()
y = x.reshape(3, 4)
y = x.reshape(3,-1)
y = x.reshape(-1,4)
y.shape

torch.Size([3, 4])

In [3]:
## 特殊的张量创建：
z1 = np.zeros((2,3,4))
print(z1)

z2 = torch.zeros((2,3,4))
print(z2)

z3 = torch.ones((2,3,4))
print(z3)

### 随机采样：
z4 = torch.randn((2,3,4))
z4

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[[ 0.8027, -2.1982,  0.2623,  0.2851],
         [-0.1363,  0.5375, -0.1894, -0.4603],
         [ 1.6977, -1.5352,  1.1770,  1.4251]],

        [[ 0.6744,  0.0191, -1.1389, -1.4574],
         [-0.2104, -0.5383, -1.1860, -0.8717],
         [ 0.6331,  0.0719,  1.2197, -0.4323]]])

### $\S2.1.2$ 运算符

In [4]:
# 运算符
## element-wise:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x+y, "\n", x-y, "\n", x*y, "\n", x/y, "\n", x**y)
print(torch.exp(x))

tensor([ 3,  4,  6, 10]) 
 tensor([-1,  0,  2,  6]) 
 tensor([ 2,  4,  8, 16]) 
 tensor([0.5000, 1.0000, 2.0000, 4.0000]) 
 tensor([ 1,  4, 16, 64])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [5]:
# 张量连接：
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
## 不同的dim代表不同的方向:
torch.concat((X,Y), dim=0), torch.concat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [6]:
# 通过逻辑运算符构建二元张量：
X == Y

# 对张量的元素求和：
X.sum(dim=0)

tensor([12., 15., 18., 21.])

### $\S2.1.3$ 广播机制
对于两个维数不同的张量，仍然有可能通过广播机制进行相互运算。

In [7]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a, "\n", b)
a+b

tensor([[0],
        [1],
        [2]]) 
 tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

### $\S2.1.4$ 索引和切片

In [8]:
# 张量的切片:
print(X)
X[-1]
X[1:3]

## 连续索引返回的的是视图:
X[1,2] = 9
print(X)

## 切片返回的是视图:
X[0:2, :] = 12
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


### $\S2.1.5$ 内存节省

In [11]:
## 在这个赋值过程中，Y重新指向了新的内存空间:
before = id(Y)
Y = Y + X
id(Y) == before

## 原地修改变量内存的方法——通过切片索引:
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
Z[:] = X + Y
print("new id(Z):", id(Z))

## 原地修改变量内存的方法——通过特定操作符：
print("id(Y):", id(Y))
Y += X+Y
print("new id(Y):", id(Y))

id(Z): 2164568860016
new id(Z): 2164568860016
id(Y): 2163938065200
new id(Y): 2163938065200


### $\S2.1.6$ 转换为其他Python对象

In [14]:
# 转换为ndarray对象:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

# 转换为Python标量:
a = torch.tensor([3.5])
a, a.item(), int(a), float(a)

(tensor([3.5000]), 3.5, 3, 3.5)

## $\S2.2$ 数据预处理